// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(nuvio_coreFFI)
import nuvio_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_nuvio_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_nuvio_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNuvioCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * A catalog or collection of content items (movies, TV shows, etc.)
 *
 * All fields use UniFFI-compatible types (no lifetimes, no generics) to ensure
 * safe FFI export to Kotlin and Swift.
 */
public struct Catalog: Equatable, Hashable {
    /**
     * Unique identifier for this catalog
     */
    public var id: String
    /**
     * Display name of the catalog (e.g., "Action Movies", "Trending Now")
     */
    public var name: String
    /**
     * Optional description of the catalog
     */
    public var description: String?
    /**
     * List of content item IDs contained in this catalog
     * References Meta.id values to avoid embedding full objects across FFI
     */
    public var itemIds: [String]
    /**
     * Optional URL to catalog cover/banner image
     */
    public var coverUrl: String?
    /**
     * Optional sort order for displaying this catalog (lower numbers appear first)
     */
    public var sortOrder: Int32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier for this catalog
         */id: String, 
        /**
         * Display name of the catalog (e.g., "Action Movies", "Trending Now")
         */name: String, 
        /**
         * Optional description of the catalog
         */description: String?, 
        /**
         * List of content item IDs contained in this catalog
         * References Meta.id values to avoid embedding full objects across FFI
         */itemIds: [String], 
        /**
         * Optional URL to catalog cover/banner image
         */coverUrl: String?, 
        /**
         * Optional sort order for displaying this catalog (lower numbers appear first)
         */sortOrder: Int32?) {
        self.id = id
        self.name = name
        self.description = description
        self.itemIds = itemIds
        self.coverUrl = coverUrl
        self.sortOrder = sortOrder
    }

    

    
}

#if compiler(>=6)
extension Catalog: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCatalog: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Catalog {
        return
            try Catalog(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf), 
                itemIds: FfiConverterSequenceString.read(from: &buf), 
                coverUrl: FfiConverterOptionString.read(from: &buf), 
                sortOrder: FfiConverterOptionInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Catalog, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterSequenceString.write(value.itemIds, into: &buf)
        FfiConverterOptionString.write(value.coverUrl, into: &buf)
        FfiConverterOptionInt32.write(value.sortOrder, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCatalog_lift(_ buf: RustBuffer) throws -> Catalog {
    return try FfiConverterTypeCatalog.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCatalog_lower(_ value: Catalog) -> RustBuffer {
    return FfiConverterTypeCatalog.lower(value)
}


/**
 * Metadata for a content item (movie, TV show, etc.)
 *
 * All fields use UniFFI-compatible types (no lifetimes, no generics) to ensure
 * safe FFI export to Kotlin and Swift.
 */
public struct Meta: Equatable, Hashable {
    /**
     * Unique identifier for this content item
     */
    public var id: String
    /**
     * Display name of the content
     */
    public var name: String
    /**
     * Optional description or synopsis
     */
    public var description: String?
    /**
     * Optional URL to poster image
     */
    public var posterUrl: String?
    /**
     * Optional URL to background image
     */
    public var backgroundUrl: String?
    /**
     * Optional IMDB identifier (e.g., "tt1234567")
     */
    public var imdbId: String?
    /**
     * Optional TMDB (The Movie Database) identifier
     */
    public var tmdbId: Int32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier for this content item
         */id: String, 
        /**
         * Display name of the content
         */name: String, 
        /**
         * Optional description or synopsis
         */description: String?, 
        /**
         * Optional URL to poster image
         */posterUrl: String?, 
        /**
         * Optional URL to background image
         */backgroundUrl: String?, 
        /**
         * Optional IMDB identifier (e.g., "tt1234567")
         */imdbId: String?, 
        /**
         * Optional TMDB (The Movie Database) identifier
         */tmdbId: Int32?) {
        self.id = id
        self.name = name
        self.description = description
        self.posterUrl = posterUrl
        self.backgroundUrl = backgroundUrl
        self.imdbId = imdbId
        self.tmdbId = tmdbId
    }

    

    
}

#if compiler(>=6)
extension Meta: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMeta: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Meta {
        return
            try Meta(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf), 
                posterUrl: FfiConverterOptionString.read(from: &buf), 
                backgroundUrl: FfiConverterOptionString.read(from: &buf), 
                imdbId: FfiConverterOptionString.read(from: &buf), 
                tmdbId: FfiConverterOptionInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Meta, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterOptionString.write(value.posterUrl, into: &buf)
        FfiConverterOptionString.write(value.backgroundUrl, into: &buf)
        FfiConverterOptionString.write(value.imdbId, into: &buf)
        FfiConverterOptionInt32.write(value.tmdbId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeta_lift(_ buf: RustBuffer) throws -> Meta {
    return try FfiConverterTypeMeta.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMeta_lower(_ value: Meta) -> RustBuffer {
    return FfiConverterTypeMeta.lower(value)
}


/**
 * A user profile with personalization settings
 *
 * All fields use UniFFI-compatible types (no lifetimes, no generics) to ensure
 * safe FFI export to Kotlin and Swift.
 */
public struct Profile: Equatable, Hashable {
    /**
     * Unique identifier for this profile
     */
    public var id: String
    /**
     * Display name of the profile (e.g., "John", "Kids")
     */
    public var name: String
    /**
     * Optional URL to profile avatar image
     */
    public var avatarUrl: String?
    /**
     * Whether this is a kids profile (affects content filtering)
     */
    public var isKids: Bool
    /**
     * Optional PIN code for profile access protection
     */
    public var pin: String?
    /**
     * Optional preferred language code (e.g., "en", "es", "fr")
     */
    public var language: String?
    /**
     * Optional autoplay next episode setting
     */
    public var autoplayNext: Bool?
    /**
     * Optional maturity rating limit (e.g., "G", "PG", "PG-13", "R")
     */
    public var maturityRating: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier for this profile
         */id: String, 
        /**
         * Display name of the profile (e.g., "John", "Kids")
         */name: String, 
        /**
         * Optional URL to profile avatar image
         */avatarUrl: String?, 
        /**
         * Whether this is a kids profile (affects content filtering)
         */isKids: Bool, 
        /**
         * Optional PIN code for profile access protection
         */pin: String?, 
        /**
         * Optional preferred language code (e.g., "en", "es", "fr")
         */language: String?, 
        /**
         * Optional autoplay next episode setting
         */autoplayNext: Bool?, 
        /**
         * Optional maturity rating limit (e.g., "G", "PG", "PG-13", "R")
         */maturityRating: String?) {
        self.id = id
        self.name = name
        self.avatarUrl = avatarUrl
        self.isKids = isKids
        self.pin = pin
        self.language = language
        self.autoplayNext = autoplayNext
        self.maturityRating = maturityRating
    }

    

    
}

#if compiler(>=6)
extension Profile: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProfile: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Profile {
        return
            try Profile(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                avatarUrl: FfiConverterOptionString.read(from: &buf), 
                isKids: FfiConverterBool.read(from: &buf), 
                pin: FfiConverterOptionString.read(from: &buf), 
                language: FfiConverterOptionString.read(from: &buf), 
                autoplayNext: FfiConverterOptionBool.read(from: &buf), 
                maturityRating: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Profile, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.avatarUrl, into: &buf)
        FfiConverterBool.write(value.isKids, into: &buf)
        FfiConverterOptionString.write(value.pin, into: &buf)
        FfiConverterOptionString.write(value.language, into: &buf)
        FfiConverterOptionBool.write(value.autoplayNext, into: &buf)
        FfiConverterOptionString.write(value.maturityRating, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProfile_lift(_ buf: RustBuffer) throws -> Profile {
    return try FfiConverterTypeProfile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProfile_lower(_ value: Profile) -> RustBuffer {
    return FfiConverterTypeProfile.lower(value)
}


/**
 * Represents a video stream with quality and format information
 *
 * All fields use UniFFI-compatible types (no lifetimes, no generics) to ensure
 * safe FFI export to Kotlin and Swift.
 */
public struct Stream: Equatable, Hashable {
    /**
     * Unique identifier for this stream
     */
    public var id: String
    /**
     * URL to the stream content
     */
    public var url: String
    /**
     * Optional quality level (e.g., "1080p", "720p", "4K")
     */
    public var quality: String?
    /**
     * Optional format/protocol (e.g., "hls", "dash", "mp4")
     */
    public var format: String?
    /**
     * Optional bitrate in kbps
     */
    public var bitrate: Int32?
    /**
     * Optional video codec (e.g., "h264", "h265", "vp9")
     */
    public var codec: String?
    /**
     * Optional audio language code (e.g., "en", "es", "fr")
     */
    public var language: String?
    /**
     * Optional URL to subtitle/caption file
     */
    public var subtitleUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unique identifier for this stream
         */id: String, 
        /**
         * URL to the stream content
         */url: String, 
        /**
         * Optional quality level (e.g., "1080p", "720p", "4K")
         */quality: String?, 
        /**
         * Optional format/protocol (e.g., "hls", "dash", "mp4")
         */format: String?, 
        /**
         * Optional bitrate in kbps
         */bitrate: Int32?, 
        /**
         * Optional video codec (e.g., "h264", "h265", "vp9")
         */codec: String?, 
        /**
         * Optional audio language code (e.g., "en", "es", "fr")
         */language: String?, 
        /**
         * Optional URL to subtitle/caption file
         */subtitleUrl: String?) {
        self.id = id
        self.url = url
        self.quality = quality
        self.format = format
        self.bitrate = bitrate
        self.codec = codec
        self.language = language
        self.subtitleUrl = subtitleUrl
    }

    

    
}

#if compiler(>=6)
extension Stream: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStream: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Stream {
        return
            try Stream(
                id: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                quality: FfiConverterOptionString.read(from: &buf), 
                format: FfiConverterOptionString.read(from: &buf), 
                bitrate: FfiConverterOptionInt32.read(from: &buf), 
                codec: FfiConverterOptionString.read(from: &buf), 
                language: FfiConverterOptionString.read(from: &buf), 
                subtitleUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Stream, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterOptionString.write(value.quality, into: &buf)
        FfiConverterOptionString.write(value.format, into: &buf)
        FfiConverterOptionInt32.write(value.bitrate, into: &buf)
        FfiConverterOptionString.write(value.codec, into: &buf)
        FfiConverterOptionString.write(value.language, into: &buf)
        FfiConverterOptionString.write(value.subtitleUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStream_lift(_ buf: RustBuffer) throws -> Stream {
    return try FfiConverterTypeStream.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStream_lower(_ value: Stream) -> RustBuffer {
    return FfiConverterTypeStream.lower(value)
}


/**
 * Error types that can occur in the Nuvio Core SDK.
 *
 * All variants use named fields to ensure compatibility with UniFFI's FFI layer.
 * These errors can be safely propagated across language boundaries to Kotlin and Swift.
 */
public enum NuvioError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Error occurred during serialization or deserialization
     */
    case SerializationError(
        /**
         * Detailed error message describing what went wrong
         */msg: String
    )
    /**
     * Error occurred during validation of input data
     */
    case ValidationError(
        /**
         * Detailed error message describing the validation failure
         */msg: String
    )
    /**
     * Unknown or unexpected error occurred
     */
    case Unknown(
        /**
         * Detailed error message describing the error
         */msg: String
    )
    /**
     * Network error occurred during HTTP request
     */
    case NetworkError(
        /**
         * Detailed error message describing the network failure
         */msg: String
    )
    /**
     * Operation timed out
     */
    case Timeout(
        /**
         * Detailed error message describing the timeout
         */msg: String
    )
    /**
     * Addon not found
     */
    case AddonNotFound(
        /**
         * ID of the addon that was not found
         */addonId: String
    )
    /**
     * Invalid addon manifest
     */
    case InvalidManifest(
        /**
         * Detailed error message describing the manifest validation failure
         */msg: String
    )
    /**
     * Response size exceeds limit
     */
    case ResponseTooLarge(
        /**
         * Actual size of the response in bytes
         */size: UInt64, 
        /**
         * Maximum allowed size in bytes
         */maxSize: UInt64
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension NuvioError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNuvioError: FfiConverterRustBuffer {
    typealias SwiftType = NuvioError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NuvioError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .SerializationError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ValidationError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Unknown(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .NetworkError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Timeout(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .AddonNotFound(
            addonId: try FfiConverterString.read(from: &buf)
            )
        case 7: return .InvalidManifest(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 8: return .ResponseTooLarge(
            size: try FfiConverterUInt64.read(from: &buf), 
            maxSize: try FfiConverterUInt64.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NuvioError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .SerializationError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .ValidationError(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Unknown(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .NetworkError(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Timeout(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .AddonNotFound(addonId):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(addonId, into: &buf)
            
        
        case let .InvalidManifest(msg):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .ResponseTooLarge(size,maxSize):
            writeInt(&buf, Int32(8))
            FfiConverterUInt64.write(size, into: &buf)
            FfiConverterUInt64.write(maxSize, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNuvioError_lift(_ buf: RustBuffer) throws -> NuvioError {
    return try FfiConverterTypeNuvioError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNuvioError_lower(_ value: NuvioError) -> RustBuffer {
    return FfiConverterTypeNuvioError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_nuvio_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNuvioCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all