#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 003: Enhanced Multi-Profile Support

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PROJECT INFO
# ============================================
echo ""
echo "Project: Enhanced Multi-Profile Support"
echo "Tech: React Native + TypeScript (TV support)"
echo ""

# ============================================
# CHECK DEPENDENCIES
# ============================================
echo "Checking dependencies..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found - please install Node.js${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found - please install npm${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check .env.local
if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}⚠ .env.local not found - creating from .env.example${NC}"
    if [ -f ".env.example" ]; then
        cp .env.example .env.local
        echo -e "${YELLOW}Please configure .env.local with your API keys${NC}"
    else
        echo -e "${RED}✗ .env.example not found${NC}"
        exit 1
    fi
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================
echo ""
echo "Installing dependencies..."
npm install

# ============================================
# START MAIN SERVICE
# ============================================
echo ""
echo "Starting React Native development server..."
npm run start &

# Wait for Expo dev server
echo ""
wait_for_service 19000 "Expo Dev Server" || {
    echo -e "${YELLOW}Note: Expo dev server might be on a different port or using cloud bundler${NC}"
}

# ============================================
# SUMMARY
# ============================================
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main App:         http://localhost:3000"
echo "  Expo Dev Tools:   http://localhost:19002"
echo ""
echo "Development Commands:"
echo "  npm run start        - Start development server"
echo "  npm run ios          - Run on iOS simulator"
echo "  npm run android      - Run on Android emulator"
echo "  npm run start:tv     - Start TV variant"
echo ""
echo "TV Testing:"
echo '  npm run ios -- --simulator="Apple TV"   - Run on Apple TV'
echo "  npm run android -- --deviceId=AndroidTV - Run on Android TV"
echo ""
echo "Next Steps:"
echo "1. Open iOS Simulator or Android Emulator"
echo "2. Press 'i' for iOS or 'a' for Android in the terminal"
echo "3. For TV: Use --simulator='Apple TV' or Android TV device ID"
echo ""
echo "Profile Testing:"
echo "- Create multiple profiles to test isolation"
echo "- Watch different content on each profile"
echo "- Verify continue watching differs per profile"
echo "- Test profile switcher with TV remote"
echo ""
echo -e "${GREEN}Happy coding!${NC}"
echo ""
